env_id: LunarLander-v2
total_timesteps: 600000
update_steps: 4096
num_updates: null
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
learning_rate: 0.0003
batch_size: 512
update_epochs: 10
seed_list: [0, 1, 2]
early_stop_avg: 260
log_interval: 10
eval_interval: 100
